### ISSUE TITLE
Figure out why (or if) `extraConfig` is needed for push secret

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/binderhub-service#113]
While working on https://github.com/2i2c-org/infrastructure/issues/4133, apparently push secret needed to be set twice:

```
  extraConfig:
    # FIXME: set KubernetesBuildExecutor.push_secret again
    #        without this for some reason the build pods
    #        search after the wrong secret name (i.e. the default name)
    #        set by binderhub in KubernetesBuildExecutor.push_secret
    01-binderhub-service-set-push-secret: |
      import os
      c.KubernetesBuildExecutor.push_secret = os.environ["PUSH_SECRET_NAME"]
```

understand why, and fix it so we don't need to do that.

**Comment by consideRatio** [comment]
@sgibson91 you didnt duplicate this part in the new hub right, and it still worked? If so, i figure we can close this.

**Comment by sgibson91** [comment]
I didn't know anything about this so I didn't implement it

**Comment by consideRatio** [comment]
>I think the reasons for this ending up could have been that a restart led to a already running build pod was detected, and that it then reported the same error because it had not been re-created with the relevant credentials setup after the binderhub pod was restarted.
>
>I really don't know, but removing this config and starting a fresh build pod works.
