### ISSUE TITLE
Draft plan of work towards a standalone demo

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/binderhub-service#15]
We want to work twoards making a demonstrative use of the binderhub-service chart to build/push images using repo2docker, both from the API and the web UI.

- BinderHub PR: https://github.com/jupyterhub/binderhub/pull/1647
  - @GeorgianaElena will focus on this
- Configuring BinderHub the software through the binderhub-service Helm chart
  - @consideRatio will focus on this
- Explore and figure out the need for [image-builder daemonset](https://github.com/jupyterhub/binderhub/blob/main/helm-chart/binderhub/templates/container-builder/daemonset.yaml) to prepare nodes with a container runtime
- Test binderhub's ability to build/push in the CI system

### Out of scope

- Image cleaner

These are drafts planned between me and @GeorgianaElena, to be continued!

**Comment by damianavila** [comment]
@consideRatio, do you feel this is the goal issue we have discussed in the dedicated meeting we had and, if that is not the case, can we update it to represent the agreements we have reached? I am trying to have a representation of each of the quarterly goals in dedicated issues so I can group them in a goals-dedicated view in our Eng board. Thanks!

**Comment by arnim** [comment]
Do we have an approximate eta for this / #19 that we can communicate?

**Comment by consideRatio** [comment]
The work towards a demo environment of testing things has been completed. Let's switch to #19 for a followup on the outcomes.
