### ISSUE TITLE
Create a fork of binderhub to develop opt-out feature of not launching following build/push

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/binderhub-service#6]

**Comment by yuvipanda** [comment]
Can you tell me what you mean by a 'fork' in this context?

**Comment by consideRatio** [comment]
I mean a github repository fork of jupyterhub/binderhub to develop and trial the feature to upstream to jupyterhub/binderhub after success.

**Comment by yuvipanda** [comment]
I would love for us to have a WIP PR on the binderhub repo from the start, primarily to make sure we don't end up writing code that is not acceptable to be merged. The smaller the diffs, the better. However, we do not need to wait for those to first get merged before continuing testing.

For this specifically, I would suggest a traitlet that adds a conditional to not launch.

**Comment by consideRatio** [comment]
I've opened https://github.com/jupyterhub/binderhub/pull/1647 as a placeholder PR, and used my personal repo consideratio/binderhub as a fork - but the PR branch can be pushed to by jupyterhub/binderhub maintainers.
